language: node_js
node_js:
 - "0.11"
 - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - "npm install"
  - "npm test"
